config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  resources :devise
  root 'posts#index'

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  # validates :name, presence: true, length: { minimum: 5 }
  # validates :body, presence: true, length: { minimum: 15 }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    # if @comment.save
      redirect_to post_path(@post)
    # else
    #   render 'new'
    # end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
		@posts = Post.all.order("updated_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

	def show
    @post = Post.find(params[:id])
	end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete

    redirect_to root_path
  end

  private
    def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><i><%= time_ago_in_words(comment.created_at) %> ago</i></p>
	</div>

	<% if user_signed_in? %>
		<p> <%= link_to "Delete", [comment.post, comment], method: :delete, class: "button", data: { confirm: "Are you sure?" } %> </p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<% if @post.comments.build.errors.any? %>
		<div id="errors">
			<h2> <%= pluralize(@post.comments.build.errors.count, "error") %> stopped this Comment from saving </h2>
			<ul>
				<% @post.comments.build.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
				<% end %>
			</ul>
		</div>
  	<% end %>
  
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<br>
		<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TumblrClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="sidebar">
      <ul class="">
        <li class="category"><%= link_to "Tumblr", root_path %></li>
        <li><%= link_to "Posts", root_path %></li>
        <li> <%= link_to "About", about_path %> </li>
      </ul>

      <% if !user_signed_in? %>
        <p class="sign_in"><%= link_to "User Login", new_user_session_path %></p>
      <% end %>
    </div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>Post Feed</p>
        <% elsif current_page?(about_path) %>
          <%= link_to "<<", root_path, class: "button" %>
          <p>Personal Site</p>
        <% else %>
          <%= link_to "Back to Post Feed", root_path %>
        <% end %>
        <% if user_signed_in? %>
          <div class="buttons">
            <button class="button"><%= link_to "Make Post", new_post_path %></button>
            <button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
          </div>
        <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
      <% end %>

      <%= yield %>

    </div>
    
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
    <div id="profile_image">
        <%= image_tag "profile.png" %>
    </div>
    <div id="content">
        <h1>Avatar</h1>
        <p>You probably haven't heard of them mustache swag yr forage polaroid kinfolk salvia food truck XOXO jianbing taxidermy. Asymmetrical selvage green juice, air plant mlkshk chartreuse cloud bread jianbing austin readymade hashtag beard. YOLO etsy meggings fam kickstarter green juice selfies. Lyft snackwave distillery semiotics hashtag kombucha narwhal copper mug pork belly aesthetic. Dreamcatcher letterpress poutine microdosing cardigan woke.</p>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2> <%= pluralize(@post.errors.count, "error") %> stopped this post from saving </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
    <h1>Fix Post</h1>

    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
   <div class="post_wrapper">
        <h2 class="title"><%= link_to post.title, post %></h2>
        <p class="body"><%= truncate(post.body, length:100) %></p>
        <p class="date"><%= time_ago_in_words( post.updated_at ) %> ago</p>
    </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
    <h1>New Post</h1>

    <%= render 'form' %>
    
</div>

app/views/posts/show.html.erb
<div id="post_content">
    <h1 class="title">
    <%= @post.title %>
    </h1>

    <p class="date">
        <span class="date-created">
            Submitted <%= time_ago_in_words(@post.created_at) %>
        </span>

        <span class="date-updated">
            Updated <%= time_ago_in_words(@post.updated_at) %>
        </span> 
        
        <% if user_signed_in? %> 
            <%= link_to "Edit", edit_post_path(@post), class: "button" %> | 
            <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %> 
        <% end %>
    </p>

    <p class="body">
        <%= @post.body %>
    </p>
    
    <div id="comments">
        <h2> <%= @post.comments.count %> Comments</h2>
        <%= render @post.comments %>
        <h3> Join the discussion: </h3>
        <%= render "comments/form" %>
    </div>
</div>